import {useState} from "react";import{Link}from"react-router-dom";import{searchDirectAdminUsers,getDirectAdminUser,applyDirectAdminAction}from"../services/adminDirectService";import{showInSiteAlert}from"../utils/inSiteDialog";import"./AdminDirectManagement.css";
const labels={warning:"اخطار مستقیم",user_suspend:"تعلیق حساب",user_restore:"رفع تعلیق حساب",chat_restrict:"محدودکردن گفتگو",chat_restore:"رفع محدودیت گفتگو",pair_block:"قطع ارتباط دو کاربر",pair_unblock:"رفع قطع ارتباط",listing_disable:"غیرفعال‌کردن آگهی",listing_enable:"فعال‌کردن آگهی"};
const reasons=[["policy_violation","نقض قوانین فضاجو"],["harassment","مزاحمت یا رفتار نامناسب"],["spam","اسپم یا پیام‌های تکراری"],["fraud_risk","رفتار مشکوک یا خطر کلاهبرداری"],["fake_info","اطلاعات یا هویت مشکوک"],["listing_issue","تخلف مرتبط با آگهی"],["safety","حفاظت از ایمنی کاربران"],["other","سایر دلایل مدیریتی"]];
const fa=v=>v?new Intl.DateTimeFormat("fa-IR-u-ca-persian",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
export default function AdminDirectManagement(){const[q,setQ]=useState("");const[results,setResults]=useState([]);const[data,setData]=useState(null);const[action,setAction]=useState("warning");const[reasonCode,setReason]=useState("policy_violation");const[note,setNote]=useState("");const[chatId,setChat]=useState("");const[spaceId,setSpace]=useState("");const[relatedUserId,setRelated]=useState("");const[busy,setBusy]=useState(false);const[shown,setShown]=useState(20);
async function search(e){e?.preventDefault();try{setBusy(true);setResults(await searchDirectAdminUsers(q))}catch(e){showInSiteAlert(e.message)}finally{setBusy(false)}}
async function open(id){try{setBusy(true);setData(await getDirectAdminUser(id));setResults([]);setAction("warning");setNote("");setChat("");setSpace("");setRelated("");setShown(20)}catch(e){showInSiteAlert(e.message)}finally{setBusy(false)}}
async function submit(e){e.preventDefault();if(!data)return;try{setBusy(true);await applyDirectAdminAction({action,targetUserId:data.user.id,reasonCode,note,chatId:chatId||null,spaceId:spaceId||null,relatedUserId:relatedUserId||null});if(["listing_disable","listing_enable"].includes(action)){window.dispatchEvent(new Event("fazajoo:spaces-changed"));}showInSiteAlert("اقدام مستقیم مدیریتی با موفقیت ثبت و اجرا شد.");await open(data.user.id)}catch(e){showInSiteAlert(e.message)}finally{setBusy(false)}}
return <main className="direct-admin"><section className="direct-admin__hero"><div><span>🛡 مدیریت مستقل فضاجو</span><h1>مدیریت مستقیم کاربران</h1><p>بدون نیاز به گزارش تخلف یا پرونده حقوقی؛ با علت اجباری، اعلان استاندارد و ردپای کامل.</p></div><Link to="/admin">بازگشت به مدیریت</Link></section><section className="direct-admin__body"><form className="direct-admin__search" onSubmit={search}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="شماره موبایل یا نام کاربر"/><button disabled={busy}>جستجو</button></form>
{results.length>0&&<div className="direct-admin__results">{results.map(u=><button key={u.id} onClick={()=>open(u.id)}><strong>{u.full_name||"کاربر فضاجو"}</strong><span>{u.phone}</span><em>{u.is_active?"فعال":"تعلیق‌شده"}</em></button>)}</div>}
{data&&<><section className="direct-admin__profile"><div><h2>{data.user.full_name||"کاربر فضاجو"}</h2><p>{data.user.phone} • {data.user.account_type==="agent"?"مشاور املاک":"کاربر عادی"}</p></div><b className={data.user.is_active?"active":"suspended"}>{data.user.is_active?"حساب فعال":"حساب تعلیق‌شده"}</b></section>
<form className="direct-admin__action" onSubmit={submit}><h3>اقدام مستقیم مدیریتی</h3><label>نوع اقدام<select value={action} onChange={e=>setAction(e.target.value)}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>
{["chat_restrict","chat_restore"].includes(action)&&<label>گفتگو<select value={chatId} onChange={e=>setChat(e.target.value)} required><option value="">انتخاب گفتگو</option>{data.chats.map(c=><option key={c.id} value={c.id}>{c.title} — {c.other_name||c.other_phone||"کاربر"} — {c.moderation_mode==="blocked"?"محدود":"فعال"}</option>)}</select></label>}
{["listing_disable","listing_enable"].includes(action)&&<label>آگهی<select value={spaceId} onChange={e=>setSpace(e.target.value)} required><option value="">انتخاب آگهی</option>{data.spaces.map(s=><option key={s.id} value={s.id}>{s.title} — {s.status}</option>)}</select></label>}
{["pair_block","pair_unblock"].includes(action)&&<label>کاربر دوم<select value={relatedUserId} onChange={e=>setRelated(e.target.value)} required><option value="">انتخاب از گفتگوهای این کاربر</option>{[...new Map(data.chats.map(c=>[c.other_user_id,c])).values()].map(c=><option key={c.other_user_id} value={c.other_user_id}>{c.other_name||"کاربر فضاجو"} — {c.other_phone}</option>)}</select></label>}
<label>علت اقدام<select value={reasonCode} onChange={e=>setReason(e.target.value)}>{reasons.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>توضیح داخلی مدیر<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="علت و مستندات تصمیم را کوتاه و روشن ثبت کنید..." required minLength={3}/></label><p className="direct-admin__hint">این توضیح داخلی برای کاربر نمایش داده نمی‌شود و در ردپای مدیریتی باقی می‌ماند.</p><button className="execute" disabled={busy}>ثبت و اجرای اقدام</button></form>
<section className="direct-admin__history"><h3>ردپای اقدامات مستقیم مدیریتی</h3>{data.history.length===0?<p>هنوز اقدام مستقیمی برای این کاربر ثبت نشده است.</p>:data.history.slice(0,shown).map(h=><article key={h.id}><strong>{labels[h.action_type]||h.action_type}</strong><span>{h.admin_name||"مدیر فضاجو"} • {fa(h.created_at)}</span><small>علت: {h.reason_code}</small><p>{h.note}</p></article>)}{shown<data.history.length&&<button onClick={()=>setShown(x=>x+20)}>نمایش بیشتر</button>}</section></>}
</section></main>}
