export const emptyVillaDetails = {
  bedrooms: "",
  capacity: "",
  extraGuestPrice: "",
  distanceToSea: "",
  distanceToForest: "",
  checkInTime: "14:00",
  checkOutTime: "12:00",
  houseRules: "",
  pool: false,
  heatedPool: false,
  parking: false,
  yard: false,
  furnished: true,
  barbecue: false,
  airConditioning: false,
  heating: false,
  wifi: false,
  petFriendly: false,
};
